"""Provider-independent message protocol used by the agent runtime."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TypeAlias


@dataclass(frozen=True, slots=True)
class UserPromptPart:
    """User input included in a model request."""

    content: str


@dataclass(frozen=True, slots=True)
class TextPart:
    """Text generated by a model."""

    content: str


ModelRequestPart: TypeAlias = UserPromptPart
ModelResponsePart: TypeAlias = TextPart


@dataclass(slots=True)
class ModelRequest:
    """A provider-independent request sent to a model."""

    parts: list[ModelRequestPart] = field(default_factory=list)


@dataclass(slots=True)
class ModelResponse:
    """A provider-independent response returned by a model."""

    parts: list[ModelResponsePart] = field(default_factory=list)

    @property
    def text(self) -> str:
        """Join all text parts in response order."""
        return "".join(part.content for part in self.parts)


ModelMessage: TypeAlias = ModelRequest | ModelResponse
